pipeline {
    agent any
     stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Poojithadevops/GitOps-devops-project.git'
                 
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Building Application..."'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying Application..."'
            }
        }
    }
}
