pipeline {
    agent any
    tools {
        maven "maven 3.9.9"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Poojithadevops/GitOps-devops-project.git'
            }
        }
        
        stage('Build') {
            steps {
                sh "mvn clean package"  # Build WAR file (if using Maven)
                
            }
        }
        
        stage('Deploy') {
            steps {
                echo "Deploying Application to Tomcat..."
                 sh "scp -o StrictHostKeyChecking=no target/*.war ec2-user@3.147.195.82:/opt/apache-tomcat-9.0.100/webapps/"
                
            }
        }
    }
}
