pipeline {
    agent any
     options {
        timeout(time: 10, unit: 'MINUTES')  // Correct syntax for timeout
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Poojithadevops/GitOps-devops-project.git'
                 
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Building Application..."'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Deploying Application..."'
            }
        }
    }
}
